# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brad Rathke
email: me@brad-rathke.com
description: > # this means to ignore newlines until "baseurl:"
  Brad Rathke's personal blog, covering topics in machine learning and computer graphics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.brad-rathke.com" # the base hostname & protocol for your site
twitter_username: brad_rathke
github_username:  brad-rathke

# Build settings
markdown: kramdown

gems: ['jekyll-sitemap']
include: ['_pages', '_posts', '_publications']
exclude: ['Gemfile', 'Gemfile.lock', 'readme.md', '.gitignore', '.git', '_data', '_scripts', '_site']

relative_permalinks: false
permalink: pretty


kramdown:
  input: GFM
  hard_wrap: false
  highlighter: pygments.rb

feed:
  path: atom.xml
  
author:
  name: Brad Rathke
  picture: /img/bradrathke.png
  twitter: brad_rathke
  github: brad-rathke

related:
  max_count: 5
  min_score: .1
  accuracy: .75

collections:
  - publications
